export const TOGGLE_PANEL = 'TOGGLE_PANEL';
export const LOAD_PANEL_ITEMS = 'LOAD_PANEL_ITEMS';
export const PANEL_CONTENT_LOADING = 'PANEL_CONTENT_LOADING';
export const SORT_PANEL_CONTENT_BY_AUTHOR = 'SORT_PANEL_CONTENT_BY_AUTHOR';
export const SORT_PANEL_CONTENT_BY_TITLE = 'SORT_PANEL_CONTENT_BY_TITLE';
export const SORT_PANEL_CONTENT_BY_ANSWERS = 'SORT_PANEL_CONTENT_BY_ANSWERS';