export const SEARCH_RESULTS_LOADING = 'SEARCH_RESULTS_LOADING';
export const SEARCH_RESULTS_ERROR = 'SEARCH_RESULTS_ERROR';
export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SORT_RESULTS_BY_AUTHOR = 'SORT_RESULTS_BY_AUTHOR';
export const SORT_RESULTS_BY_TITLE = 'SORT_RESULTS_BY_TITLE';