export const GET_TAG_QUESTIONS_LOADING = 'GET_TAG_QUESTIONS_LOADING';
export const GET_TAG_QUESTIONS_ERROR = 'GET_TAG_QUESTIONS_ERROR';
export const GET_TAG_QUESTIONS_SUCCESS = 'GET_TAG_QUESTIONS_SUCCESS';
