export const GET_USER_QUESTIONS_LOADING = 'GET_USER_QUESTIONS_LOADING';
export const GET_USER_QUESTIONS_ERROR = 'GET_USER_QUESTIONS_ERROR';
export const GET_USER_QUESTIONS_SUCCESS = 'GET_USER_QUESTIONS_SUCCESS';
